#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(Sensor, in1,    agl_claw,       sensorAnalog)
#pragma config(Sensor, in8,    Gyro,           sensorGyro)
#pragma config(Sensor, dgtl1,  hgt_limit,      sensorDigitalIn)
#pragma config(Sensor, dgtl2,  enc_moveR,      sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  enc_updown,     sensorQuadEncoder)
#pragma config(Sensor, dgtl11, enc_moveL,      sensorQuadEncoder)
#pragma config(Motor,  port1,           mtr_UpD_R_D,   tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           mtr_UpD_L_U,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           mtr_LF,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           mtr_LB,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           mtr_claw_left, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           mtr_UpD_R_U,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           mtr_RF,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           mtr_RB,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           mtr_claw_right, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          mtr_UpD_L_D,   tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "includes.c"

task main()
{
	nVolume = 80;
	warning_func(2,800);
	wait_for_playtone();
	warning_func(1,666);
	wait_for_playtone();
	warning_func(1,800);
	wait_for_playtone();

	pre_auton();

	startTask(disp_logo);
	startTask(para_calc_task);

while(1){
	while(1)
	{
		if(vexRT[Btn7R]) break;
		else if(vexRT[Btn7U])
		{
			startTask(autonomous);
			while(1) if(vexRT[Btn7R])
			{
				stopTask(autonomous);
				stop_all_motors();
				wait1Msec(50);
				break;
			}
		}
	  else if(vexRT[Btn7D])
	  {
			startTask(usercontrol);
			while(1) if(vexRT[Btn7R])
			{
				stopTask(usercontrol);
				wait1Msec(50);
				break;
			}
		}
		wait1Msec(50);
	}
	wait1Msec(50);
}
	while(1)
		wait1Msec(1500);
}
